# Inserts a blank line between shell prompts
add_newline = true

# timeout
command_timeout = 1000

# Use powerline format for better terminal integration
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"

# Configure directory display
[directory]
style = "blue bold"
truncation_length = 3
truncate_to_repo = true

# Configure git branch
[git_branch]
symbol = " "
style = "bold purple"

# Configure git status
[git_status]
style = "red bold"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

# Show command duration for long commands
[cmd_duration]
min_time = 2_000
show_milliseconds = false
format = "took [$duration](bold yellow)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Configure hostname for remote connections
[hostname]
ssh_only = true
format = "[@$hostname](bold red) "

